#!/bin/bash

. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"

install_ansible ${test_ansible_version}
ansible_plugins


assert_ansible_syntax

assert_playbook_runs
assert_playbook_idempotent


